//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class listmv
    {
        public int id { get; set; }
        public string tenphim { get; set; }
        public string tacgia { get; set; }
        public Nullable<System.DateTime> namphathanh { get; set; }
        public string theloai { get; set; }
    }
}
